// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYkJDXLe559FpwXl0HoL-7sUFwSN1Vc4',
    appId: '1:268853907281:android:51508d9d003b6d93a9cd70',
    messagingSenderId: '268853907281',
    projectId: 'meditation-6f139',
    databaseURL: 'https://meditation-6f139-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meditation-6f139.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT1NDlzlPm_l-BZZzeCE0R4ZLLQ5iZY_8',
    appId: '1:268853907281:ios:57949b99c28ac2baa9cd70',
    messagingSenderId: '268853907281',
    projectId: 'meditation-6f139',
    databaseURL: 'https://meditation-6f139-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'meditation-6f139.appspot.com',
    androidClientId: '268853907281-nren9lilplbgv7mcbi2bricf8eibhidr.apps.googleusercontent.com',
    iosClientId: '268853907281-17g5sph3i025ksc3m3nji7pvcl4i5k7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationAppFlutter',
  );
}
